---
title: "Project"
author: "Katy Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# Load in functions
source("R/projectCode.R")
Rcpp::sourceCpp("src/projectCode.cpp")
```

100 Bootstrap runs, n = 100

Scenario 1: $$p_1 = 0.5, p_2 = 0.5, \mu_1 = 0, mu_2 = 0.5$$

```{r}
table1 = simulations(c(.5,.5), c(0, .5), 100)
colnames(table1) = c("P1", "P2", "Theta1", "Theta2")
knitr::kable(table1)
table1 = cbind(table1, Diff = .5)
```

Scenario 2: $$p_1 = 0.5, p_2 = 0.5, \mu_1 = 0, mu_2 = 1$$

```{r}
table2 = simulations(c(.5,.5), c(0, 1), 100)
colnames(table2) = c("P1", "P2", "Theta1", "Theta2")
knitr::kable(table2)
table2 = cbind(table2, Diff = rep(1, 4))
```

Scenario 3: $$p_1 = 0.5, p_2 = 0.5, \mu_1 = 0, \mu_2 = 1.5$$

```{r}
table3 = simulations(c(.5,.5), c(0, 1.5), 100)
colnames(table3) = c("P1", "P2", "Theta1", "Theta2")
knitr::kable(table3)
table3 = cbind(table3, Diff = rep(1.5, 4))
```

Scenario 4: $$p_1 = 0.5, p_2 = 0.5, \mu_1 = 0, \mu_2 = 2$$

```{r}
table4 = simulations(c(.5,.5), c(0, 2), 100)
colnames(table4) = c("P1", "P2", "Lambda 1", "Lambda 2")
knitr::kable(table4)
table4 = cbind(table4, Diff = rep(2, 4))
```

```{r}
plot_df = as.data.frame(rbind(table1, rbind(table2, rbind(table3, table4))))
plot_df = cbind(Method = rep(c("Non-Parametric", "COMPLH", "DISTLAT", "Strat"), 4), plot_df)
write.csv(plot_df, "first_table.csv", row.names = FALSE)

p1 = plot_simulations(1, c("P1", "P2", "Theta1", "Theta2"), plot_df, "P", "", 
                      "Coverage Probability")
p2 = plot_simulations(3, c("P1", "P2", "Theta1", "Theta2"), plot_df, "Lambda 1", "Difference in Lambdas", "")
p3 = plot_simulations(4, c("P1", "P2", "Theta1", "Theta2"), plot_df, "Lambda 2", "", "")
ggsave("first_grid.jpeg",ggpubr::ggarrange(p1, p2, p3, common.legend = TRUE, nrow = 1),
       width = 10, height =7)
```

100 Bootstrap runs, n = 100

Scenario 1: $$p_1 = 0.2, p_2 = 0.8, \mu_1 = 0, \mu_2 = 0.5$$

```{r}
table1_2 = simulations(c(.2,.8), c(0, .5), 100)
colnames(table1_2) = c("P1", "P2", "Theta1", "Theta2")
knitr::kable(table1_2)
table1_2 = cbind(table1_2, Diff = rep(.5, 4))
```

Scenario 2: $$p_1 = 0.2, p_2 = 0.8, \mu_1 = 0, \mu_2 = 1$$

```{r}
table2_2 = simulations(c(.2,.8), c(0, 1), 100)
colnames(table2_2) = c("P1", "P2", "Theta1", "Theta2")
knitr::kable(table2_2)
table2_2 = cbind(table2_2, Diff = rep(1, 4))
```

Scenario 4: $$p_1 = 0.2, p_2 = 0.8, \mu_1 = 0, \mu_2 = 2$$

```{r}
table3_2 = simulations(c(.2,.8), c(0, 1.5), 100)
colnames(table3_2) = c("P1", "P2", "Theta1", "Theta2")
knitr::kable(table3_2)
table3_2 = cbind(table3_2, Diff = rep(1.5, 4))
```

Scenario 4: $$p_1 = 0.2, p_2 = 0.8, \mu_1 = 0, \mu_2 = 2$$

```{r}
table4_2 = simulations(c(.2,.8), c(0, 2), 100)
colnames(table4_2) = c("P1", "P2", "Theta1", "Theta2")
knitr::kable(table4_2)
table4_2 = cbind(table4_2, Diff = rep(2, 4))
```

```{r}
plot_df2 = as.data.frame(rbind(table1_2, rbind(table2_2, rbind(table3_2, table4_2))))
plot_df2 = cbind(Method = rep(c("Non-Parametric", "COMPLH", "DISTLAT", "Strat"), 4),plot_df2)
write.csv(plot_df2, "second_table.csv", row.names = FALSE)
p1 = plot_simulations(1, c("P1", "P2", "Theta1", "Theta2"), plot_df2, "P", "", 
                      "Coverage Probability")
p2 = plot_simulations(3, c("P1", "P2", "Theta1", "Theta2"), plot_df2, "Lambda 1", "Difference in Lambdas", "")
p3 = plot_simulations(4, c("P1", "P2", "Theta1", "Theta2"), plot_df2, "Lambda 2", "", "")
ggsave("second_grid.jpeg",ggpubr::ggarrange(p1, p2, p3, common.legend = TRUE, nrow = 1),
       width = 10, height =7)
```

100 Bootstrap runs, n = 100

Scenario 1: $$\pi_1 = \pi_2 = \pi_3 = \pi_4 = 0.25, \mu_1 = 0, \mu_2 = 1, \mu_3 = 2, \mu_4 = 3$$
```{r}
table1_3 = simulations4(rep(1/4,4), seq(0, 3, 1), 100)
colnames(table1_3) = c("P1", "P2", "P3", "P4", 
                     "Theta1", "Theta2", "Theta3", "Theta4")
knitr::kable(table1_3)
table1_3 = cbind(table1_3, Diff = rep(sqrt(sum(seq(0, 3, 1)^2)), 8))
```
Scenario 2:
```{r}
table2_3 = simulations4(rep(1/4,4), seq(0, 6, 2), 100)
colnames(table2_3) = c("P1", "P2", "P3", "P4", 
                     "Theta1", "Theta2", "Theta3", "Theta4")
knitr::kable(table2_3)
table2_3 = cbind(table2_3, Diff = rep(sqrt(sum(seq(0, 6, 2)^2)), 4))
```

Scenario 3:
```{r}
table3_3 = simulations4(rep(1/4,4), seq(0, 9, 3), 100)
colnames(table3_3) = c("P1", "P2", "P3", "P4", 
                     "Theta1", "Theta2", "Theta3", "Theta4")
knitr::kable(table3_3)
table3_3 = cbind(table3_3, Diff = rep(sqrt(sum(seq(0, 9, 3)^2)), 4))
```

Scenario 4:
```{r}
table4_3 = simulations4(rep(1/4,4), seq(0, 12, 4), 100)
colnames(table4_3) = c("P1", "P2", "P3", "P4", 
                     "Theta1", "Theta2", "Theta3", "Theta4")
knitr::kable(table4_3)
table4_3 = cbind(table4_3, Diff = rep(sqrt(sum(seq(0, 12, 4)^2)), 4))
```

```{r}
plot_df3 = as.data.frame(rbind(table1_3, rbind(table2_3, rbind(table3_3, table4_3))))
plot_df3 = cbind(Method = rep(c("Non-Parametric", "COMPLH", "DISTLAT", "Strat"), 4), plot_df3)
write.csv(plot_df3, "third_table.csv", row.names = FALSE)
p1 = plot_simulations(5, c("P1", "P2", "P3", "P4", "Theta1", "Theta2", "Theta3", "Theta4"), plot_df3, "Lambda 1", "", 
                      "Coverage Probability")
p2 = plot_simulations(6,c("P1", "P2", "P3", "P4", "Theta1", "Theta2", "Theta3", "Theta4"), 
                      plot_df3, "Lambda 2", "Difference in Lambdas", "")
p3 = plot_simulations(7, c("P1", "P2", "P3", "P4", "Theta1", "Theta2", "Theta3", "Theta4"), 
                      plot_df3, "Lambda 3", "", "")
p4 = plot_simulations(8, c("P1", "P2", "P3", "P4", "Theta1", "Theta2", "Theta3", "Theta4"),
                      plot_df3, "Lambda 4", "", "")
ggsave("third_grid.jpeg",ggpubr::ggarrange(p1, p2, p3,p4, common.legend = TRUE, nrow = 1),
       width = 10, height =7)
```

```{r}
plot_clusters = function(true_p, true_theta, n) {
  # Simulate Data
  p_multi = rmultinom(n, 1, true_p)
  dens = matrix(c(rnorm(n, true_theta[1]), rnorm(n, true_theta[2]), 
                  rnorm(n, true_theta[3]), rnorm(n, true_theta[4])), ncol = 4)
  
  data = p_multi[1,]*dens[1,] + p_multi[2,]*dens[2,] + 
    p_multi[3,]*dens[3,] + p_multi[4,]*dens[4,]
  
  # Get initial values from kmeans
  initial_theta = sort(kmeans(data, 4)$centers[,1])
  initial_p = sort(kmeans(data, 4)$size / length(data))
  
  # Perform EM
  em_result = em_norm4(data, initial_p, initial_theta, classes = TRUE)
  
  theta_hat = em_result[[2]]
  p_hat = em_result[[1]]
      
  # Set number of iterations
  iterations = 1000
      
  # Perform Stratified Bootstrap
  w2_tot = em_result[[4]]
  w1_tot = em_result[[3]]
  w3_tot = em_result[[5]]
  w4_tot = em_result[[6]]
  
  df = data.frame(w1_tot, 
                 w2_tot, w3_tot, w4_tot)
  df = df %>%
        rowwise() %>%
        mutate(Classification = ifelse(w1_tot == max(w1_tot, w2_tot, w3_tot, w4_tot), 1, 
                                       ifelse(w2_tot == max(w1_tot, w2_tot, w3_tot, w4_tot), 2,
                                              ifelse(w3_tot == max(w1_tot, w2_tot, 
                                                                   w3_tot, w4_tot), 3, 4))))
      
  # Perform Non Parametric Bootstrap
  theta = matrix(nrow = 0, ncol = 8)
  for (i in 1:1000) {
    s = as.matrix(sample(data, length(data), replace = TRUE))
    reg_list = em_norm4(s, p_hat, theta_hat, classes = TRUE)
    w1_tot = reg_list[[3]]
    w2_tot = reg_list[[4]]
    w3_tot = reg_list[[5]]
    w4_tot = reg_list[[6]]
    
    df_reg = data.frame(w1_tot, 
                 w2_tot, w3_tot, w4_tot)
    df_reg = df %>%
        rowwise() %>%
        mutate(Classification = ifelse(w1_tot == max(w1_tot, w2_tot, w3_tot, w4_tot), 1, 
                                       ifelse(w2_tot == max(w1_tot, w2_tot, w3_tot, w4_tot), 2,
                                              ifelse(w3_tot == max(w1_tot, w2_tot, 
                                                                   w3_tot, w4_tot), 3, 4))))
  }

t = em_norm4(s, p_hat, theta_hat, classes = TRUE)
  
  
  return(table)
}
```